name = "bcmwriter"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "SESSIONS"
id = "2ce2a8daf192495bba413fc8a1f6c4a6"
preview_id = "2ce2a8daf192495bba413fc8a1f6c4a6"

[vars]
FRONTEND_URL = "https://bigcatmellow.github.io"
GOOGLE_CLIENT_ID = "224286904313-1kqc1e0k3a0dk88ut9m7c76trlgsjahp.apps.googleusercontent.com"