name = "bcmwriter-api"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "SESSIONS"
id = "2ce2a8daf192495bba413fc8a1f6c4a6"
preview_id = "2ce2a8daf192495bba413fc8a1f6c4a6"

[vars]
FRONTEND_URL = "https://bigcatmellow.github.io"
GOOGLE_DRIVE_FOLDER = "1HDSoa7EThzo15nkwWlb2RURzBWNxSIAe"