name = "bcmwriter"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SESSIONS"
id = "2ce2a8daf192495bba413fc8a1f6c4a6"
preview_id = "2ce2a8daf192495bba413fc8a1f6c4a6"

[vars]
ALLOWED_ORIGINS = "http://localhost:8000,http://localhost:3000,https://bigcatmellow.github.io"
APP_ORIGINS = "http://localhost:8000,https://bigcatmellow.github.io/BCMWriter/"
OAUTH_CALLBACK_BASE = "https://bcmwriter.goldenjanitors.workers.dev"
GOOGLE_DRIVE_FOLDER = "1HDSoa7EThzo15nkwWlb2RURzBWNxSIAe"
GOOGLE_CLIENT_ID = "224286904313-f3u6k9lgenovbth9mi47biflh7vmi05k.apps.googleusercontent.com"



# Secrets are set via CLI, not in this file
# Run: wrangler secret put GITHUB_CLIENT_ID
# Run: wrangler secret put GITHUB_CLIENT_SECRET
